export const OfflineAudioCompletionEvent = window?.OfflineAudioCompletionEvent
// export const AudioProcessingEvent = window?.AudioProcessingEvent
// export const AudioRenderCapacityEvent = window?.AudioRenderCapacityEvent
export const BaseAudioContext = window?.BaseAudioContext
export const AudioContext = window?.AudioContext
export const OfflineAudioContext = window?.OfflineAudioContext
// export const ScriptProcessorNode = window?.ScriptProcessorNode
export const AudioWorkletNode = window?.AudioWorkletNode
export const AnalyserNode = window?.AnalyserNode
export const AudioBufferSourceNode = window?.AudioBufferSourceNode
export const BiquadFilterNode = window?.BiquadFilterNode
export const ChannelMergerNode = window?.ChannelMergerNode
export const ChannelSplitterNode = window?.ChannelSplitterNode
export const ConstantSourceNode = window?.ConstantSourceNode
export const ConvolverNode = window?.ConvolverNode
export const DelayNode = window?.DelayNode
export const DynamicsCompressorNode = window?.DynamicsCompressorNode
export const GainNode = window?.GainNode
export const IIRFilterNode = window?.IIRFilterNode
export const MediaStreamAudioSourceNode = window?.MediaStreamAudioSourceNode
export const OscillatorNode = window?.OscillatorNode
export const PannerNode = window?.PannerNode
export const StereoPannerNode = window?.StereoPannerNode
export const WaveShaperNode = window?.WaveShaperNode
export const AudioNode = window?.AudioNode
export const AudioScheduledSourceNode = window?.AudioScheduledSourceNode
export const AudioParam = window?.AudioParam
export const AudioDestinationNode = window?.AudioDestinationNode
export const AudioListener = window?.AudioListener
export const AudioWorklet = window?.AudioWorklet
export const AudioParamMap = window?.AudioParamMap
// export const AudioRenderCapacity = window?.AudioRenderCapacity
export const PeriodicWave = window?.PeriodicWave
export const AudioBuffer = window?.AudioBuffer
